### PR TITLE
chore: v3 Update

### LINKED ISSUE #531: Release: v3 App Merge
Merge dev branch into master for v3 app release

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #531 

Dev merge into master for v3 update

@mejariamol Please test the release build so we can merge this

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@mejariamol @Shailesh351 @heysadboy Please test if the app is working on all fronts

Credentials 

Server URL - https://open-event-api.herokuapp.com/v1/
Email - test@test.in
Password - tester

Thanks

**Comment by heysadboy** [comment]
@iamareebjamal It shows this when I try to open the link screenshot 13

**Comment by iamareebjamal** [comment]
@heysadboy Use it in the app server link section it'll work :smile:

**Comment by heysadboy** [comment]
Sorry about that @iamareebjamal I am looking into that.

**Comment by iamareebjamal** [comment]
You are trying the Google Play version and not the development branch

**Comment by iamareebjamal** [comment]
@mejariamol @Shailesh351 Please you try this too so we can speed up the process

**Comment by iamareebjamal** [comment]
@mariobehling @niranjan94 Please merge

**Pull request merged**
