### PR TITLE
chore: Migrate to AndroidX

### LINKED ISSUE #1562: Migrate to AndroidX
**Describe the chore**
Migrate the project to AndroidX

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1562 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream development branch.

Changes: 

Updated project to use AndroidX.

### CODE REVIEW

**Comment by ShridharGoel** [comment]
@iamareebjamal 

CircleCI is failing because of this:

```
Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by ShridharGoel** [comment]
@iamareebjamal Any idea why there are data binding errors? It's building successfully and working in proper manner locally.

**Comment by iamareebjamal** [comment]
Run ./gradlew build locally, and other commands mentioned in the CI to check what's wrong

**Comment by ShridharGoel** [comment]
> Run ./gradlew build locally, and other commands mentioned in the CI to check what's wrong

No build issues when run locally.

**Comment by iamareebjamal** [comment]
And other command work as well?

**Comment by iamareebjamal** [comment]
It's not databinding error, it's annotation processing error

**Comment by ShridharGoel** [comment]
> It's not databinding error, it's annotation processing error

Yes I realised that later

**Comment by ShridharGoel** [comment]
> And other command work as well?

Just tried `./gradlew lint androidCheck androidPmd` and it failed with the same error.

**Comment by iamareebjamal** [comment]
Try individually

**Comment by ShridharGoel** [comment]
Do we need to disable incremental compilation?

**Comment by iamareebjamal** [comment]
No

**Comment by ShridharGoel** [comment]
> Try individually

`./gradlew lint` and `./gradlew androidCheck` failed

**Comment by iamareebjamal** [comment]
Hmm. Fix the issues and it'll work. 👍

**Comment by ShridharGoel** [comment]
https://github.com/google/dagger/issues/298

**Comment by iamareebjamal** [comment]
A 3 year old issue, which got triggered by migrating to AndroidX. I don't think so

**Comment by ShridharGoel** [comment]
`javax/xml/bind/JAXBException`

I'm also seeing this in the logs

**Comment by iamareebjamal** [comment]
@ShridharGoel Resolve conflicts

**Comment by ShridharGoel** [comment]
DataBinding errors

**Pull request closed without merging**
