### PR TITLE
fix: Confirm password filling automatically on device rotation

### LINKED ISSUE #1374: Confirm Password automatically gets filled up on device rotation
**Describe the bug**
The confirm password field in the SignUp Activity automatically gets filled up with your password if you rotate the device. 

**To Reproduce**
1. Go to Sign up activity 
2. Click on Password and type your password
3. Rotate the device .
4. The confirm password field automatically gets filled

**Expected behavior**
It should not automatically get filled.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One plus 5|
|Android Version|e.g. Oreo 8.1 |

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by tavishjain**
Fixes #1374 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream development branch.

Changes: Removed the user.password field from confirm password edit text, which populated the confirm password edit text when the device screen was rotated. 
Explanation : When the user entered the password, the password was stored in an object of the User class. When the screen was rotated, the confirm password edit text referred the same field, which caused that field to get filled with the same password that was entered by the user in the password field. 

Screenshots for the change:

Previous behaviour:
ezgif com-video-to-gif

Current behaviour:
ezgif com-video-to-gif

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This breaks the 2 way binding?

**Comment by tavishjain** [comment]
@iamareebjamal I didnt understand what you are trying to ask

**Comment by tavishjain** [comment]
What was happeing was thatthe confirm password field was directly connected to the password filed, which has been removed

**Comment by iamareebjamal** [comment]
Change title to follow semantic pull request guidelines

**Pull request merged**
