### PR TITLE
fix: Correct FAB size and position (#708)

### LINKED ISSUE #708: Correct FAB size and position
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

In some screens, 'add' Floating Action Buttons seems to be oddly positioned, squashed to the corner. 
As per the Material Design guidelines,"The floating action button should be placed 16dp minimum from the edge on mobile and 24dp minimum on tablet/desktop."

- [ ] In `event_create_layout.xml`, `marginBottom` for FAB is missing.
- [ ] In `ticket_create_layout`, distance from parent view edges is not same (might be the desired behaviour). `marginTop` is missing here.

**Expected Behaviour**

`marginBottom` attribute should be present in FAB in `event_create_layout.xml`
add `marginTop` attribute to `ticket_create_layout.xml`

**Screenshots of the issue**

badui

fab1

fab2

**Android version and Phone Model**

Android version: 6.0.1; Phone model: Xiaomi Redmi 4A 
    
**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mishuvs**
Fixes #708 

Changes: FABs positioned correctly so as to have 16dp of space from the edges. Margin added to the layout for 'Code of Conduct', so that FAB doesn't block its veiw.

Screenshots for the change: 
fab41
fab3
fab4
fab2

### CODE REVIEW

**Comment by iamareebjamal** [comment]
It looks a little bit out of place in Create Ticket Fragment

**Comment by mishuvs** [comment]
@iamareebjamal So what do you suggest?

**Comment by iamareebjamal** [comment]
Align the create ticket text. Or actually, just remove the Bottom Sheet Fragment and make it a proper fragment

**Comment by mishuvs** [comment]
I think the content is pretty short for it to be a proper fragment. Besides that, I think the Bottom Sheet Fragment looks and feels good :sweat_smile: .
Can I just align the text for now?

**Comment by iamareebjamal** [comment]
Alright, also show how the layout looks when creating ticket, i.e. with progress bar

**Comment by mishuvs** [comment]
It looks like this:
fab

**Comment by iamareebjamal** [comment]
Try adding the progress bar above fab as this does not look good

**Comment by mishuvs** [comment]
Adding progress bar above, didn't seem to work. However, increasing the size seemed to be a better solution to make it look the same as it was before. Looks like this:
fab2

**Comment by mishuvs** [comment]
Adding progress bar above seemed to not work. Instead, I increased the size of ProgressBar.
Looks like this:
fab3

**Pull request merged**
