### PR TITLE
feature: Enter recovery token to request new password

### LINKED ISSUE #578: Enter recovery token and request new password
Parent Issue #548 

**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

**Feature Description**

User will enter the recovery token received on his email along with a new password to reset his password. Server will then patch the previous password associated with that email.
 
**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Masquerade0097**
fixes #578
parent #548

Changes: User enters the token  he received via email along ith new password to change his account's password in case he forgots it.

Screenshots for the change: 
screen-upd

### CODE REVIEW

**Comment by Masquerade0097** [comment]
@iamareebjamal Please review. Also please give suggestions regarding where to put the resend token link. I was thinking of replacing the text to - `Didn't receive token? Resend` and the position of link to be between Token and password TextInputLayout.

**Comment by iamareebjamal** [comment]
@Masquerade0097 Yup, please go ahead, also, please add additional repeat password field

**Comment by Masquerade0097** [comment]
@iamareebjamal What do you mean by repeat password field?

**Comment by Masquerade0097** [comment]
@iamareebjamal Please have a look.

**Pull request merged**
