### PR TITLE
chore: Changed BASE URL for release build

### LINKED ISSUE #1322: Change BASE URL for release version
### Chore

**Description**

BASE URL should be changed to `next.eventyay.com`.

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #1322 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 

Screenshots for the change:

### CODE REVIEW

**Comment by Masquerade0097** [comment]
Obtaining HTTP 404 on `http://next.eventyay.com/`.

**Comment by srv-twry** [comment]
@Masquerade0097 Could you please try `api.eventyay.com` ? I think `next.eventyay.com` is the frontend deployment. If it doesn't work, feel free to ping @Kreijstal on the server channel. He is handling the deployment.

**Comment by Masquerade0097** [comment]
@iamareebjamal Mario was insisting that we should use the latest API deployment in our master branch which is also being used in next.eventyay.com.
@srv-twry What API is frontend next.eventyay.com is using?

**Comment by iamareebjamal** [comment]
Backend guys should add SSL support to `api.eventyay.com`

@Kreijstal

**Comment by srv-twry** [comment]
@Masquerade0097 
> What API is frontend next.eventyay.com is using?

As I said, I am not aware of the deployment stuff. If my memory serves well, @maxlorenz @Kreijstal and @bhaveshAn were handling it. Feel free to ping them here or on the channel. Thanks.

**Comment by bhaveshAn** [comment]
> What API is frontend next.eventyay.com is using?

As @srv-twry told it's http://api.eventyay.com

**Comment by Masquerade0097** [comment]
@iamareebjamal So I guess we can keep on using `https://open-event-api-master.herokuapp.com/v1/` till SSL support is added for `api.eventyay.com`. Closing this.

**Pull request closed without merging**
