### PR TITLE
chore: Removed Activity and Fragment instantiation tests

### LINKED ISSUE #686: Remove activity and fragment instantiation tests
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [x] Chore

### Chore

**Description**

The activity and fragment instantiation tests are flaky and reak with every upgrade of tools. They are used to test the dependency injection and are surely first line of defence to know if the app crashes without any user interaction and the wiring of the app is correct. They also provide a lot of coverage to the project but having flaky tests is worse than having no tests, so until we have a good way to test the instantiation of activities and fragments, they should be disabled for good

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fixes #686 

Changes: The Activity and Fragment instantiation tests were removed.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Don't remove the classes, just comment out the annotations

**Comment by sridharjajoo** [comment]
I have removed the unused imports as well

**Comment by iamareebjamal** [comment]
@sridharjajoo Please fix he build

**Comment by sridharjajoo** [comment]
@iamareebjamal As the annotations have been commented out , the build is failing.

**Comment by iamareebjamal** [comment]
You have to test the build locally that it is working before sending the PR. Not all annotations need to be disabled. Check which ones need to stay on

**Comment by sridharjajoo** [comment]
@iamareebjamal Instead of commenting out , can I use the @Ignore notation for the classes?

**Pull request merged**
