### PR TITLE
chore: Change Share menu to Done menu option

### LINKED ISSUE #1529: Remove the share button from the toolbar in the UpdateEventFragment
**Describe the feature you'd like**
The share option in the toolbar of UpdateEventFragment should be removed, as it is implemented in the navigation drawer menu item.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by kush-mish**
**Fixes #1529**

**Checklist**
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream development branch.
- [ ] I have checked for PMD and check-style issues 

**Changes**
- Changes the share menu item to the done menu item in the UpdateEventFragment toolbar.
- Removes the green **Done** button from the bottom of the layout.

**Screenshot**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
You have removed the validation

**Comment by kush-mish** [comment]
Shouldn't there be an "Event Updated successfully" toast/snackbar notification?

**Comment by Masquerade0097** [comment]
@kush-mish There should be a toast with the success message.

**Comment by Masquerade0097** [comment]
By mistake

**Comment by kush-mish** [comment]
@Masquerade0097 please help with this here 👉 https://github.com/fossasia/open-event-orga-app/commit/4e737fd51973cce9ffa243055975f63f4b4be6eb#commitcomment-32665496

**Comment by kush-mish** [comment]
@iamareebjamal can't this be merged?

**Pull request merged**
