### PR TITLE
feat: Add and configure LeakCanary (#129)

### LINKED ISSUE #129: Add LeakCanary to detect memory leaks
Add and configure LeakCanary to detect leaks and fix them

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #129

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@mejariamol Please review

**Comment by mejariamol** [comment]
@iamareebjamal setting up leakcanary in the app will be in another PR right ?

**Comment by iamareebjamal** [comment]
It's added and ready @mejariamol 

That's the beauty :)

**Comment by iamareebjamal** [comment]
@mejariamol Please take a look now

**Comment by iamareebjamal** [comment]
@niranjan94 Please merge

**Pull request merged**
