### PR TITLE
feat: Add dependency injection using dagger

### LINKED ISSUE #145: Add Dagger2 for Dependency Injection
We have a great testing environment, but that also means that we have lots of class dependencies and have to configure them the same way in each object.

We should use Dagger 2 for DI

I'm working on it

### PR DESCRIPTION
**Pull request by iamareebjamal**
- Add dagger and configure it for different modules
-  Add start method in presenters instead of attach
- Modify tests accordingly
- Normalize model names

Fixes #145

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@mejariamol Please review

Had to normalize several components so PR is big

**Comment by iamareebjamal** [comment]
@mejariamol Please review as implementing dbflow on non dagger environment will be a bit problematic

**Comment by mejariamol** [comment]
Yeah sure. I will review soon. I am getting familiar with it. :)

**Comment by iamareebjamal** [comment]
@niranjan94 Please merge

**Pull request merged**
