### PR TITLE
feat: Add attendees to persistence layer

### LINKED ISSUE #187: Add attendees to persistence layer
Add attendees in database

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #187 

Depends on #188, so, to be merged after that

- Add attendees to database
- Update models to include relevant relations
- Update tests

App Structure is finally stable

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@mejariamol @arp95 @Shailesh351 @mahikaw @rohanagarwal94 Please review

**Comment by mejariamol** [comment]
@iamareebjamal please change PR title.

**Comment by iamareebjamal** [comment]
@mejariamol To what?

**Comment by iamareebjamal** [comment]
@niranjan94 Please merge

**Pull request merged**
