### PR TITLE
fix: Prevent false error while creating events

### LINKED ISSUE #1514: event can't be added to the app
**Describe the bug**
<not able to login with the given credentials >

**To Reproduce**
<Steps to reproduce the behavior:
1. Go to 'app'
2. Click on the app and enter the email id  orgadeveloper@gmail.com and password "fossasia"'

4. See error  error 401 unauthorized>

**Expected behavior**
< It should log in
 into the app>

**Logs**

**Screenshots**
<[whatsapp image 2019-02-19 at 1 30 49 pm](https://user-images.githubusercontent.com/35845477/52999265-51bc5780-344b-11e9-8fb2-741f4bb0d06a.jpeg) >

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 5A|
|Android Version|Oreo    |

**Would you like to work on the issue?**

- [ ] Yes

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1514 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream development branch.

Changes: 

Passed the context of the activity instead of the EventDetailsStepThree and UpdateEventFragment fragments in ViewModelProviders to prevent the 'Event name cannot be empty' error message.
Because of this, SingleEventLiveData had to be changed to MutableLiveData.

### CODE REVIEW

**Comment by kush-mish** [comment]
But what about the error messages which were referred [here]((https://github.com/fossasia/open-event-orga-app/commit/4e737fd51973cce9ffa243055975f63f4b4be6eb#commitcomment-32557612))?

**Comment by ShridharGoel** [comment]
@kush-mish Everything is working fine except the case when internet connection isn't available. This PR can be considered as a temporary fix for the problem of not being able to create events.

**Comment by iamareebjamal** [comment]
I don't understand why these changes will affect the errors?

**Comment by ShridharGoel** [comment]
I am also not sure about the strange behaviour. I think it's because the logic for handling the functioning of the next button (clicking which calls the verify function) is in the activity while we were passing the context of the fragments in the ViewModelProviders.

**Comment by iamareebjamal** [comment]
That's understandable. But why change single event livedata?

**Comment by ShridharGoel** [comment]
Because using SingleEventLiveData would give `Only one observer at a time may subscribe to a SingleEventLiveData` error since the same ViewModel is being shared by multiple fragments.

**Comment by ShridharGoel** [comment]
I had changed it to SingleEventLiveData in #1487 but it has created this issue.

**Pull request merged**
