### PR TITLE
chore(deps): Update gradle and dependencies

### LINKED ISSUE #1547: Update the Gradle version
**Describe the chore**
The current version of gradle contains some deprecated code, due to which the build in the PR is failing
For reference, my PR #1539 is failing due to the build error 

*registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)*

and it's solution has been mentioned here, which directly aims to update the gradle version :
https://github.com/google/play-services-plugins/issues/23#issuecomment-448919947
https://github.com/google/play-services-plugins/pull/35

**Would you like to work on the issue?**

- [ ] Yes
- [X] No
- Other:

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1547 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream development branch.

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@ShridharGoel Please test and approve

**Comment by ShridharGoel** [comment]
@iamareebjamal Sorry, saw this just now. It's working fine.

**Comment by ShridharGoel** [comment]
So we are skipping checkstyle?

**Comment by iamareebjamal** [comment]
Yes, it has some issues in latest gradle

**Comment by ShridharGoel** [comment]
Okay, that's why checkstyle error was coming.

**Pull request merged**
