### PR TITLE
fix: retain main activity state on rotation

### LINKED ISSUE #375: Handling rotation for Main Activity
To be done after #372 

Currently, on rotation main activity opens event dashboard.

Expected:
If any fragment is opened already, it should remain on rotation too.

Taking this up.

### PR DESCRIPTION
**Pull request by mejariamol**
- used publish subject instead of behavior subject for bus
- shifted initial page load logic on main activity start to main activity's onCreate
- bus is not used to show header title any more

fixes #375

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal 
have replaced behavior subject to publish subject. please test on a device. we may restore it with behavior subject again with #376. please review.

**Comment by iamareebjamal** [comment]
@mejariamol There's no point in changing something temporarily. What issue will it fix if it is PublishSubject?

**Comment by mejariamol** [comment]
Behavior subject is causing issue for rotation by re-emitting the last item to load dashboard forcefully, right?

**Comment by mejariamol** [comment]
I am just saying if we are using behavior subject then it should be used correctly.

**Comment by iamareebjamal** [comment]
Yes, that's why we should fix the behavior rather than changing it to PublishSubject. If we want to use PublishSubject, then fine. But then we must implement a solution to the problem we are facing in #364 if BehaviorSubject is not used. It will break on merging on this PR

**Comment by mejariamol** [comment]
> But then we must implement a solution to the problem we are facing in #364 if BehaviorSubject is not used

will have to use stored event id and get the event from the repository to set to ticket.

**Comment by iamareebjamal** [comment]
Then what'd be the point of a bus?

**Comment by mejariamol** [comment]
For event click on events page.

**Comment by iamareebjamal** [comment]
That's not the use of bus. For that, we could even use action listeners. This is a workaround TBH, not a solution, so we should either complete the solution or else there'd be no point of the bus. I'll be thinking about the solution, meanwhile could you take up #353 

These bugs can be solved later, as the app is working fine without them. Probably when the feature set s stable, we can take these up.

**Comment by iamareebjamal** [comment]
Handled in #389

**Pull request closed without merging**
