### PR TITLE
feat: full screen chart activity

### LINKED ISSUE #337: A separate full screen chart activity for chart display
Currently, a chart is displayed directly in the layout with other components. Which delimits many features of the chart like - scrolling, zooming.. etc 

Expected:
An option should be given to open the chart in a separate full-screen chart activity where the chart can be accessed easily. 

I am working on it.

### PR DESCRIPTION
**Pull request by mejariamol**
fixes #337 
tests shall be added in separate PR.

img_20170722_190528_232 1

screenshot_2017-07-23-17-14-25

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal
Couldn't able to decide what data will be passed to the chart activity?

**Comment by iamareebjamal** [comment]
@mejariamol Only event ID will be passed to it

**Comment by mejariamol** [comment]
How will it know which chart to be displayed? For now it is fine. But we will be using it to display other ticket charts too once ticket page is created.

**Comment by iamareebjamal** [comment]
There are only 3 ticket types @mejariamol

**Comment by mejariamol** [comment]
@iamareebjamal please review.

**Pull request merged**
