### PR TITLE
fix: UI Edits in Navigation Drawer

### LINKED ISSUE #1013: Rename Navigation Drawer items
### Chore 

**Chore Description**

Few menu items in the Drawer layout should be renamed so that the Drawer layout of Orga App looks similar to EventBrite app. This will help users to make the transition smooth for users who choose to migrate to Orga app from EventBrite app.

1. Attendees -> Check In
2. Change the Date format displayed in Drawer to `DAY, MONTH-DATE, TIME` 
3. Change Attendee Drawable.
   
**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #1013 

Changes: 
1. Renamed Attendee to Check In.
2. Changed Drawable of Drawer Menu - Check In.
3. Changed Date Display Format.

Screenshots for the change: 
Orga App
bottom

EventBrite App
eventbrite

### CODE REVIEW

**Comment by iamareebjamal** [comment]
What does `Sell` signify. We are not able to sell anything from the app right now

**Comment by Masquerade0097** [comment]
@iamareebjamal It was supposed to be synonimous to selling tickets but you are right, we arn't selling anything yet so I've changed it back.

**Comment by iamareebjamal** [comment]
Move about to absolute bottom

**Comment by Masquerade0097** [comment]
Done.

**Pull request merged**
