### PR TITLE
fix: Items in Step-2 Create Event should not hide, fix indent

### LINKED ISSUE #1273: Listing Privacy gets hidden in Step 2
**Is it a ?**

- [x] Bug Report

### Bug Report    

**Actual Behaviour**

Listing Privacy option gets hidden behind the buttons when Organizer Details section expands

**Expected Behaviour**

Should not be hidden

**Steps to reproduce it**

Check the checkbox: `Add Organizer Information` and scroll down.

**Screenshots of the issue**

### PR DESCRIPTION
**Pull request by mishuvs**
Fixes #1273 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: Adds padding and fixes indentation (GitHub diff looks messed up but only tab indents are added)

Screenshots for the change:

### CODE REVIEW

**Comment by Masquerade0097** [comment]
Avoid long commit messages, follow guidelines.

**Comment by sridharjajoo** [comment]
@mishuvs Still not following the commit guidelines

**Comment by mishuvs** [comment]
@sridharjajoo I did not understand. Can you please exactly point out the issue?

**Comment by mishuvs** [comment]
@sridharjajoo Please check.

**Pull request merged**
