### PR TITLE
fix: Typo in README.md

### LINKED ISSUE #1370: Typo in README.md
**Description**
Fix typo in the Project Structure section

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by kush-mish**
Fixing the typing error in the Project Structure section.

Fixes #1370 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream development branch.

Changes: `anf` -> `and`

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please follow PR template

**Comment by kush-mish** [comment]
Done.
Although, I don't understand why one of the checks(Codacy/PR Quality Review) is not successful.

**Comment by iamareebjamal** [comment]
Leave it be

**Comment by kush-mish** [comment]
I hope this does it.

**Pull request merged**
