### PR TITLE
feat: Show speaker details along with his/her sessions

### LINKED ISSUE #996: Show speakers details in the app along with his/her sessions
### Feature Request

**Feature Description**

The app should show the Speaker details in the application along with his/her sessions.

**Would you like to work on the issue?**

Yes

**Parent issue**

#925

### PR DESCRIPTION
**Pull request by srv-twry**
Fixes #996 

Changes: Show speaker details along with his/her sessions.

Screenshots for the change: In the thread

### CODE REVIEW

**Comment by srv-twry** [comment]
screenshot_2018-06-07-03-56-54-35


There are a couple of things still left: 
1. Get text color for speaker's name using Palette.
2. Add click action to the social media links.

@iamareebjamal Where should I add the method which would take in the url and opens it in a browser ? I don't have a presenter. Should i create a utility file ?

**Comment by iamareebjamal** [comment]
URL?

**Comment by srv-twry** [comment]
Social media links

**Comment by srv-twry** [comment]
videotogif_2018 06 08_04 42 29


@iamareebjamal Please review. 
I haven't used Palette here. I think it has already been implemented in the app but it needs to be fixed.
```
// TODO: Reimplement once Glide Palette is fixed
public final class PaletteHolder
```

**Comment by iamareebjamal** [comment]
The info card requires padding and social links can be added there only

**Comment by srv-twry** [comment]
screenshot_2018-06-08-13-22-22-57

**Comment by srv-twry** [comment]
screenshot_2018-06-08-14-04-32-06

**Pull request merged**
