### PR TITLE
Interfaces renamed to start with initial-I

### LINKED ISSUE #104: Interface name should start with "I"
As we will be using many interfaces, we should follow this practice for interface name that it should start with **I**. for example `ILoginView`, `ILoginPresenter`.

### PR DESCRIPTION
**Pull request by mejariamol**
fixes #104

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Also, please rebase with master to load new changes

**Comment by mejariamol** [comment]
Closing this PR. Creating new one.

**Comment by niranjan94** [comment]
@mejariamol please don't close PRs and create new ones like this. Always update the existing branch. When you close a PR and create a new one, we loose the connectivity of the conversation that happened on the previous PR and we now have multiple PRs linked to the issue.

**Comment by mejariamol** [comment]
@niranjan94 actually it was merge conflict occurring each time I commit. So I deleted that fork.

> we loose the connectivity of the conversation that happened on the previous PR and we now have multiple PRs linked to the issue.

yes. will take care from next time.

**Pull request closed without merging**
