### PR TITLE
feat: Create Call for Speakers

### LINKED ISSUE #1029: Create Speakers Call
### Feature Request

**Feature Description**

Functionality to create Speakers Call.

**Parent Issue**
#731 
   
**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #1029 

Changes: 
1. Organizer can create speakers call for event if it does not already exist.
2. Database change listener reflects result in UI without explicitly refreshing.

Screenshots for the change: 
20180609143518-7c011ad592 gif-2-mp4 com

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Ask to server guys about hash and privacy

**Comment by Masquerade0097** [comment]
@iamareebjamal This is the reply from Mayank about hash and privacy fields -

Hash is used for accessing private call-for-speakers announcement. It is assumed that if you know the hash then you can access the private cfs. It is shown to the organiser during event creation.
Privacy is again if the cfs is private or public
Public cfs is displayed on the frontend in the event page, but private isn't. To access the private one you need the hash.

**Comment by iamareebjamal** [comment]
OK, so they need to be set in Speaker Call?

**Comment by Masquerade0097** [comment]
@iamareebjamal The create speaker call fragment is the only place in our app where organizer can set these.

**Pull request merged**
