### PR TITLE
Login UI Improved : Textview Added

### LINKED ISSUE #749: Remove "LogIn" from Action Bar title
- [x] Feature Request
    
### Feature Request

**Feature Description**

In the Login Activity, instead of showing 'Log In' in action bar title which is very obvious looking at the screen, we can remove the action bar and display a designed textview with "Open Event Orga App from Fossasia".

### PR DESCRIPTION
**Pull request by YashishDua**
Fixes #749 

Changes: Added a textview welcoming organizer and making landing page looks like it is an app for the organiser.

Updated: 

n

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please add screenshots

**Comment by YashishDua** [comment]
Added. Review it!

**Comment by iamareebjamal** [comment]
Looks bloated, we can have a thin font instead

**Comment by YashishDua** [comment]
Changed. Review now!

**Comment by iamareebjamal** [comment]
Should this be present in signup page as well?

**Comment by YashishDua** [comment]
I don't think so! Because if he/she is login in, it means for sure an organizer is logging in. On the other hand, while signing up he/she is just a user. When signs up then becomes a organizer,

**Pull request merged**
