### PR TITLE
fix: subscribing issues due to computation scheduler

### LINKED ISSUE #274: Data loading takes longer on Events and Attendees page
sub issue of #273 

Currently the pages fails to load data sometimes and keep on showing progress bar for long. 
The reason behind misbehaviour of Computation scheduler in data loading observables. Removing it solves issue for now.
**Future action:** implement sorting in fastAdapter itself. Creating issue for the same. #275  But for now just removing computation scheduler.

### PR DESCRIPTION
**Pull request by mejariamol**
- modifies comparable interface of attendee model to trim values
- replaces computation scheduler to io scheduler in events, attendees and qr scan presenters.

fixes #274

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
@mejariamol I was working on the issue as discussed also fixing the TicketAnalyser

Also, there is no need to change computation scheduler everywhere, it is not recommended to use io scheduler for CPU bound tasks

**Comment by mejariamol** [comment]
>I was working on the issue as discussed also fixing the TicketAnalyser

yeah. I have left TicketAnalyser.
>there is no need to change computation scheduler everywhere

attendee update was not working every time on toggle check in with computation scheduler. with io it is updating every time.

**Comment by iamareebjamal** [comment]
The thing is that I took up the issue #273 

And also discussed with you in private chat. There is no point in splitting cohesive issues. They can be handled in single PR as I was working on it already. If you want to take it up, no problem, just inform beforehand from next time on

**Comment by mejariamol** [comment]
>The thing is that I took up the issue

Sorry, that was really unintentional. I thought you told me to add sorting in fastadapter hence to take events and attendees page load issue. And you would be taking ticketanalyser. Thats why I opened #274 as subissue and #275 for later. 

Really sorry again.

**Comment by iamareebjamal** [comment]
No problem, please add TODO comments wherever you have replaced computation scheduler that we need to use computation in future

**Comment by iamareebjamal** [comment]
@mejariamol No need to change anything. Please take a look at #277 and test if everything is working as expected

**Comment by mejariamol** [comment]
Correctly solved via #277 , hence closing this.

**Pull request closed without merging**
