### PR TITLE
feat: Add sentry integration

### LINKED ISSUE #302: Add sentry support in the app
https://docs.sentry.io/clients/java/modules/android/

- Create a Timber tree for logging
- Create a proxy for each exception to go though

I'm working on it

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #302 

- Add sentry integration
- Add contextmanager to set and destroy sentry context
- Redirect error and info logs to sentry

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@niranjan94 The sentry cli (in order to upload the mappings) require a sentry.properties containing project info and auth token. But we can't include it in the repo itself. However, the release build will fail without it. Any suggestions?

**Comment by niranjan94** [comment]
@iamareebjamal we can have it as a travis env variable and create the `sentry.properties` file with it in travis.yml.

**Comment by niranjan94** [comment]
Though, note that the env variable will be unavailable for PRs.

**Comment by iamareebjamal** [comment]
I think it will be better if we make the uploading option configurable, only running if user wants it?

**Comment by niranjan94** [comment]
Why do we want to upload PRs ? And we don't need release builds for PRs. 
Also, make sentry optional. Build shouldn't fail because sentry key doesn't exist. Nor should the app crash.

**Comment by iamareebjamal** [comment]
I didn't mean to say that we want to upload mappings on PR. I just meant to disable the option to upload mappings until the user explicitly enables it. 

About making sentry optional, should I create a new build variant for it?

**Comment by iamareebjamal** [comment]
@niranjan94 I have disabled the auto upload feature by default. The app does not crash if sentry key isn't present. The library is made that way. 

The build was only failing because the cli was trying to upload the mappings to sentry server, which is required for proguard based projects, but now user will just have to change that attrbute in build.gradle if he wants to enable it

**Pull request merged**
