### PR TITLE
feat: presenters via loaders

### LINKED ISSUE #196: Separate initial data load part from ui interation in presenters
Currently in presenters of event containing fragments, initial data loading part is in conjunction with a part interacting with the view. Hence data loading cannot be initialized in `onCreate` fragment call. Hence data load is called every time when switching between fragments.

If we manage to separate initial data loading as separate functions and maintain a flag to check progress and show result in view accordingly, it can be solved.

@iamareebjamal what do you think?

### PR DESCRIPTION
**Pull request by mejariamol**
fixes #196

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please review

**Comment by mejariamol** [comment]
@iamareebjamal please test.

**Comment by iamareebjamal** [comment]
@mejariamol I did, and still the resources are loaded again from db. But I guess this is not fault of the loader, it is presenter which will nevertheless load from db when start is called. Please create another issue for that.

About this PR, everything is perfect except that BaseActivity and BasePresenter have a lot of functionality in common. I think it'll be better if they share a common base class

**Comment by mejariamol** [comment]
>But I guess this is not fault of the loader, it is presenter which will nevertheless load from db when start is called. Please create another issue for that.

yeah. Will create an issue for that once this is merged. :+1:

**Comment by iamareebjamal** [comment]
OK, so just move common functions from base fragment and activity in another class

**Comment by mejariamol** [comment]
>OK, so just move common functions from base fragment and activity in another class

Actually, this can't be more abstracted. As both the classes need to extend different classes - Fragment and AppCompatActivity. So can't make another base class which will contain common function and extend these classes by that class because a class cannot extend more than one class.

Any suggestions? @iamareebjamal

**Comment by iamareebjamal** [comment]
True, my mistake

**Pull request merged**
