### PR TITLE
fix: Update check-in system to work properly

### LINKED ISSUE #1672: Check-in mechanism not working properly
**Describe the bug**
Attendee IDs are 0 due to which the check-in system is not functioning properly.

**GIF**
ezgif com-video-to-gif (78)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1672 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 

- Proper attendee IDs are being set.
- Attendee check-in status gets updated after scanning.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please summarize the changes and explain why it wasn't working and how you fixed it

**Comment by ShridharGoel** [comment]
The `getAttendeesPagewise()` method fetches the list at a particular page and appends it to the earlier list which was fetched till then. So, the `updateLocal()` method wasn't taking the correct list, it was using `attendeesList` in the presenter which had the list of attendees of just one page and not the complete list. So, I have created `getAttendeeList()` in AttendeesFragment and replaced `attendeeList` with `getView().getAttendeeList()` in AttendeesPresenter.

Apart from this, after scanning, the list was not updating until refreshed. Therefore, I've added this in the ScanQRPresenter:
```
attendee.isCheckedIn = !attendee.isCheckedIn;
        attendeeRepository.scheduleToggle(attendee)
            .subscribe(() -> {
                // Nothing to do
            }, Logger::logError);
```

**Comment by ShridharGoel** [comment]
One issue that still exists: The attendee IDs do not update when the fragment is opened for the first time. After refreshing once, the correct values show. This is because the attendees are not getting stored in the local database until refreshed once. Although we are shifting to Room and that would probably fix this, but I think this needs to be fixed right now. So, I'm working on it. 
@iamareebjamal Please tell if you have any suggestions on this.

**Comment by iamareebjamal** [comment]
I'm not able to understand why this part was needed

```java
attendeeRepository.scheduleToggle(attendee)
    .subscribe(() -> {
        // Nothing to do
    }, Logger::logError);
```

**Comment by ShridharGoel** [comment]
> I'm not able to understand why this part was needed
> 
> ```java
> attendeeRepository.scheduleToggle(attendee)
>     .subscribe(() -> {
>         // Nothing to do
>     }, Logger::logError);
> ```

To update the attendee in the local DB?

```
@NonNull
    public Completable scheduleToggle(Attendee attendee) {
        return repository
            .update(Attendee.class, attendee)
            .concatWith(completableObserver -> {
                AttendeeCheckInWork.scheduleWork();
                if (!repository.isConnected())
                    completableObserver.onError(new Exception("No network present. Added to job queue"));
            })
            .subscribeOn(Schedulers.io());
    }
```

**Comment by ShridharGoel** [comment]
`attendee.isCheckedIn = !attendee.isCheckedIn;`

This is not needed since it is being handled here:
```
if (toCheckIn) {
            getView().showMessage(
                attendee.isCheckedIn ? R.string.already_checked_in : R.string.now_checked_in,
                true
            );
            attendee.isCheckedIn = true;
        } else if (toCheckOut) {
            getView().showMessage(
                attendee.isCheckedIn ? R.string.now_checked_out : R.string.already_checked_out,
                true
            );
            attendee.isCheckedIn = false;
        }
```

**Comment by iamareebjamal** [comment]
But it was working before without it. Why is it needed now?

**Comment by ShridharGoel** [comment]
> But it was working before without it. Why is it needed now?

Wasn't working, the attendee status did not change until the list is refreshed.

**Comment by iamareebjamal** [comment]
Again, before the pagination changes, it was working. You can check in the old APK. It means this was triggered somewhere else as well. Please check the reason why it stopped working

**Comment by ShridharGoel** [comment]
Okay, checking it.

**Comment by ShridharGoel** [comment]
Scanning is working as expected. Earlier, I think I was pressing the back button quickly after scanning to go back to the list so maybe that was the reason of the list not showing updated changes or maybe it could have been because of internet connectivity issue. Reverted the changes in ScanQRPresenter.

There was an issue because of which on loading second and further pages, the data of the earlier page was getting deleted from the local DB, due to which attendee IDs started showing as 0 for the earlier pages. Updated the AttendeeRepositoryImpl to fix this.

**Comment by ShridharGoel** [comment]
> One issue that still exists: The attendee IDs do not update when the fragment is opened for the first time. After refreshing once, the correct values show. This is because the attendees are not getting stored in the local database until refreshed once. Although we are shifting to Room and that would probably fix this, but I think this needs to be fixed right now. So, I'm working on it.
> @iamareebjamal Please tell if you have any suggestions on this.

This is also fixed.

**Pull request merged**
