### PR TITLE
fix: Login and SignUp Error

### LINKED ISSUE #1191: Bugs in Login and Signup
### Bug Report    

**Actual Behaviour**

1. The user is unable to choose any other url by unchecking the checkbox in login fragment.
2.  Bug in email field validation which makes it empty on serialization.

**Android version and Phone Model**

Moto G4 Plus, nougat

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #1191 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 

Screenshots for the change:
20180711145611-7c011ad592 gif-2-mp4 com

### CODE REVIEW

**Comment by sridharjajoo** [comment]
@Masquerade0097 Will the email validation still happen?

**Comment by mishuvs** [comment]
@Masquerade0097 It is showing me "failed to connect to https://api.eventyay.com/v1". I tried un-checking the checkbox, but it is still using the above URL.

**Comment by sridharjajoo** [comment]
@iamareebjamal When using eventyay URL as the base URL , the error is popping up and we are not able to login. Is it a server side issue?

**Comment by Masquerade0097** [comment]
@mishuvs `https://api.eventyay,com/v1` has some server issues. It's down right now. Try typing dev api link in other url. It will work.

**Comment by Masquerade0097** [comment]
> Will the email validation still happen?

@sridharjajoo I've added validation check for the email. Please review.

**Pull request merged**
