### PR TITLE
feat: Confirm before logout

### LINKED ISSUE #253: Show confirm dialogue for logout
To be done after #246 is merged

Currently no confirm dialogue for logout

Expected: show confirm dialogue for logout.

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #253 

- Add a confirmation dialog before logout

device-2017-07-04-000901

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please show cancel button too. And let the title be just `Logout` and message can be `Are you sure you want to log out?`

**Comment by iamareebjamal** [comment]
Cancel will just dismiss the dialog which user can also do by clicking out of dialog or pressing back

**Comment by mejariamol** [comment]
yes. but it will be more user friendly

**Comment by iamareebjamal** [comment]
OK

**Comment by iamareebjamal** [comment]
@mejariamol Please review now

**Comment by iamareebjamal** [comment]
@niranjan94 Please merge

**Pull request merged**
