### PR TITLE
feat: Persist all entities on rotation

### LINKED ISSUE #400: Persist all entities on rotation
All entities in all views must be saved on rotation and restored accordingly

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #400 

- Refactor presenter loading and injection in fragments
- Add checks to restore persisted objects in presenter

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal Couldn't actually test the app. I am not getting a response from the server on the phone. I think some temporary issue, will try later.

**Comment by mejariamol** [comment]
@iamareebjamal Are you able to use the app? Data loading from the server not working for me?

**Comment by iamareebjamal** [comment]
@mejariamol Yes, I'm able to use it

**Comment by iamareebjamal** [comment]
@mejariamol Organizer and Events were detached due to some reason. You'll have to create event again

**Comment by iamareebjamal** [comment]
@mejariamol Please review

**Comment by iamareebjamal** [comment]
@mejariamol Please review. This is long overdue

**Comment by mejariamol** [comment]
@iamareebjamal also please let me know about the changes it is making on injecting dependencies in the fragment constructor.

**Comment by iamareebjamal** [comment]
@mejariamol The fragment variables should be immutable and never should be recreated as such. If there's a need to reset fields, presenter should do so

**Comment by iamareebjamal** [comment]
About constructor injection, almost no change is there. It just injects fields earlier than onCreate

**Pull request merged**
