### PR TITLE
Merge branch 'development'

### LINKED ISSUE #809: New release checklist
- [x] Update README with codacy badge link
- [x] Change package name to com.eventyay.organizer
- [x] Update app version
- [x] Check the app is working correctly
- [x] Merge changes to master branch

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #809 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: Merge development into master

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@Masquerade0097 @mishuvs @srv-twry @sridharjajoo Please check whether the `RELEASE` version of apk is working correctly

**Comment by Masquerade0097** [comment]
@iamareebjamal The base url `api.eventyay.com` is giving error `Failed to connect to api.eventyay`. Is it temporarily down or permanently ?

**Comment by iamareebjamal** [comment]
@Masquerade0097 It is permanently down

Use open-event-api.herokuapp.com instead

**Comment by Masquerade0097** [comment]
@iamareebjamal Ok, I'm changing it in app.

**Comment by iamareebjamal** [comment]
@srv-twry @Masquerade0097 Merge as you see fit

**Comment by iamareebjamal** [comment]
@srv-twry @sridharjajoo @Masquerade0097 @mishuvs Should this be merged now?

**Comment by sridharjajoo** [comment]
I think it can be merged

**Comment by Masquerade0097** [comment]
@iamareebjamal Yes, I think it can be merged.

**Comment by srv-twry** [comment]
@iamareebjamal Please merge. I am not sure whether to create a merge commit or just rebase and merge.

**Pull request merged**
