### PR TITLE
feat: Add lombok for data classes

### LINKED ISSUE #288: Add lombok to reduce boilerplate code in project
Models have setters and getters, toString and other general POJO methods which are hard to maintain and increase complexity of the class

Lombok uses annotation processing to generate these methods.

We can't be using Google's auto value as it enforces immutability and we want mutable classes

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #288 

- Add lombok for code generation
- Remove BaseModel from super class

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Building locally without any problem, checking why this is failing

**Comment by iamareebjamal** [comment]
@arp95 @Shailesh351 Guys could you please pull this PR and compile via terminal and tell if it is throwing errors. I am able to compile it but travis can't

```
./gradlew build
```

Should work

**Comment by Shailesh351** [comment]
@iamareebjamal Giving errors while compiling

**Comment by Shailesh351** [comment]
`Information:Gradle tasks [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources]
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
Error:(18, 54) error: cannot find symbol class DaggerAppComponent
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/events/EventListFragment.java
Error:(26, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(52, 13) error: cannot find symbol class FragmentEventListBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
Error:(20, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(38, 13) error: cannot find symbol class EventDetailBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
Error:(25, 52) error: cannot find symbol class BR
Error:(35, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(72, 13) error: cannot find symbol class FragmentAttendeesBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/checkin/AttendeeCheckInFragment.java
Error:(12, 34) error: cannot find symbol class BR
Error:(16, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(27, 13) error: cannot find symbol class BottomsheetAttendeeCheckInBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/events/EventsListAdapter.java
Error:(11, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(12, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(75, 23) error: cannot find symbol class EventLayoutBinding
Error:(79, 33) error: cannot find symbol class EventLayoutBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/events/viewholders/EventsHeaderViewHolder.java
Error:(5, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(9, 13) error: cannot find symbol class EventSubheaderLayoutBinding
Error:(11, 35) error: cannot find symbol class EventSubheaderLayoutBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/attendees/viewholders/AttendeeViewHolder.java
Error:(7, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(11, 19) error: cannot find symbol class AttendeeLayoutBinding
Error:(13, 31) error: cannot find symbol class AttendeeLayoutBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
Error:(7, 46) error: cannot find symbol class Attendee_Table
Error:(9, 46) error: cannot find symbol class Event_Table
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/checkin/AttendeeCheckInPresenter.java
Error:(8, 46) error: cannot find symbol class Attendee_Table
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/attendees/StickyHeaderAdapter.java
Error:(12, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(29, 9) error: cannot find symbol class AttendeeSubheaderLayoutBinding
Error:(31, 27) error: cannot find symbol class AttendeeSubheaderLayoutBinding
Error:*==========*class com.raizlabs.android.dbflow.processor.TableValidator (Kotlin reflection is not available) :Table org.fossasia.openevent.app.data.models.Attendee must provide a visible, default constructor.*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.TableValidator.validate(Validators.kt:182)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateDefinitions(DatabaseDefinition.kt:95)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateAndPrepareToWrite(DatabaseDefinition.kt:87)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.handle(ProcessorManager.kt:270)
Error:com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:92)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
Error:*==========*class com.raizlabs.android.dbflow.processor.TableValidator (Kotlin reflection is not available) :Table org.fossasia.openevent.app.data.models.Event must provide a visible, default constructor.*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.TableValidator.validate(Validators.kt:182)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateDefinitions(DatabaseDefinition.kt:95)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateAndPrepareToWrite(DatabaseDefinition.kt:87)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.handle(ProcessorManager.kt:270)
Error:com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:92)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
Error:*==========*class com.raizlabs.android.dbflow.processor.TableValidator (Kotlin reflection is not available) :Table org.fossasia.openevent.app.data.models.Order must provide a visible, default constructor.*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.TableValidator.validate(Validators.kt:182)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateDefinitions(DatabaseDefinition.kt:95)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateAndPrepareToWrite(DatabaseDefinition.kt:87)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.handle(ProcessorManager.kt:270)
Error:com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:92)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
Error:*==========*class com.raizlabs.android.dbflow.processor.TableValidator (Kotlin reflection is not available) :Table org.fossasia.openevent.app.data.models.Ticket must provide a visible, default constructor.*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.TableValidator.validate(Validators.kt:182)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateDefinitions(DatabaseDefinition.kt:95)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateAndPrepareToWrite(DatabaseDefinition.kt:87)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.handle(ProcessorManager.kt:270)
Error:com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:92)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
Error:*==========*class com.raizlabs.android.dbflow.processor.TableValidator (Kotlin reflection is not available) :Table org.fossasia.openevent.app.data.models.User must provide a visible, default constructor.*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.TableValidator.validate(Validators.kt:182)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateDefinitions(DatabaseDefinition.kt:95)
Error:com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition.validateAndPrepareToWrite(DatabaseDefinition.kt:87)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.handle(ProcessorManager.kt:270)
Error:com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:92)
Error:com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
Error:*==========*class com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition (Kotlin reflection is not available) :Could not find the referenced table definition org.fossasia.openevent.app.data.models.Event from SocialLink. Ensure it exists in the samedatabase org.fossasia.openevent.app.data.db.configuration.OrgaDatabase*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition.checkNeedsReferences(ForeignKeyColumnDefinition.kt:337)
Error:com.raizlabs.android.dbflow.processor.definition.TableDefinition.onWriteDefinition(TableDefinition.kt:337)
Error:com.raizlabs.android.dbflow.processor.definition.BaseDefinition.getTypeSpec(BaseDefinition.kt:130)
Error:com.raizlabs.android.dbflow.processor.utils.WriterUtils$writeBaseDefinition$1.invoke(WriterUtils.kt:16)
Error:com.raizlabs.android.dbflow.processor.utils.WriterUtils$writeBaseDefinition$1.invoke(WriterUtils.kt:11)
Error:com.grosner.kpoet.JavaFileExtensionsKt.javaFile(JavaFileExtensions.kt:9)
Error:*==========*class com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition (Kotlin reflection is not available) :Could not find the referenced table definition org.fossasia.openevent.app.data.models.Event from SocialLink. Ensure it exists in the samedatabase org.fossasia.openevent.app.data.db.configuration.OrgaDatabase*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition.checkNeedsReferences(ForeignKeyColumnDefinition.kt:337)
Error:com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition.addPropertyDefinition(ForeignKeyColumnDefinition.kt:110)
Error:com.raizlabs.android.dbflow.processor.definition.TableDefinition$onWriteDefinition$$inlined$apply$lambda$5.invoke(TableDefinition.kt:381)
Error:com.raizlabs.android.dbflow.processor.definition.TableDefinition$onWriteDefinition$$inlined$apply$lambda$5.invoke(TableDefinition.kt:29)
Error:com.raizlabs.android.dbflow.processor.utils.JavaPoetExtensionsKt.override fun(JavaPoetExtensions.kt:12)
Error:com.raizlabs.android.dbflow.processor.definition.TableDefinition.onWriteDefinition(TableDefinition.kt:370)
Error:*==========*class com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition (Kotlin reflection is not available) :Could not find the referenced table definition org.fossasia.openevent.app.data.models.Event from SocialLink. Ensure it exists in the samedatabase org.fossasia.openevent.app.data.db.configuration.OrgaDatabase*==========*
Error:java.lang.Thread.getStackTrace(Thread.java:1556)
Error:com.raizlabs.android.dbflow.processor.ProcessorManager.logError(ProcessorManager.kt:203)
Error:com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition.checkNeedsReferences(ForeignKeyColumnDefinition.kt:337)
Error:com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition.addPropertyCase(ForeignKeyColumnDefinition.kt:129)
Error:com.raizlabs.android.dbflow.processor.definition.TableDefinition$onWriteDefinition$$inlined$apply$lambda$5.invoke(TableDefinition.kt:382)
Error:com.raizlabs.android.dbflow.processor.definition.TableDefinition$onWriteDefinition$$inlined$apply$lambda$5.invoke(TableDefinition.kt:29)
Error:com.raizlabs.android.dbflow.processor.utils.JavaPoetExtensionsKt.override fun(JavaPoetExtensions.kt:12)
Error:com.raizlabs.android.dbflow.processor.definition.TableDefinition.onWriteDefinition(TableDefinition.kt:370)
Error:*==========*class com.raizlabs.android.dbflow.processor.definition.column.ForeignKeyColumnDefinition (Kotlin reflection is not available) :Could not find the referenced table definition org.fossasia.openevent.app.data.models.Event from SocialLink. Ensure it exists in the samedatabase org.fossasia.openevent.app.data.db.configuration.OrgaDatabase*==========*
Warning:File for type 'com.raizlabs.android.dbflow.config.OrgaDatabaseorga_database_Database' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 10.89 secs
Information:101 errors
Information:2 warnings`

**Comment by iamareebjamal** [comment]
Yeah, that was test build, please test now

**Comment by Shailesh351** [comment]
@iamareebjamal  Tested it. Still build failed with less errors.
It is showing cannot find symbol class DaggerAppComponent, FragmentEventListBinding etc..
Error:(26, 46) error: package org.fossasia.openevent.app.databinding does not exist

**Comment by iamareebjamal** [comment]
The actual error is the last one, can you please post that

**Comment by Shailesh351** [comment]
`Information:Gradle tasks [clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugUnitTestSources, :app:compileDebugAndroidTestSources]
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
Error:(18, 54) error: cannot find symbol class DaggerAppComponent
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/events/EventListFragment.java
Error:(26, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(52, 13) error: cannot find symbol class FragmentEventListBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/detail/EventDetailFragment.java
Error:(20, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(38, 13) error: cannot find symbol class EventDetailBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/attendees/AttendeesFragment.java
Error:(25, 52) error: cannot find symbol class BR
Error:(35, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(72, 13) error: cannot find symbol class FragmentAttendeesBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/checkin/AttendeeCheckInFragment.java
Error:(12, 34) error: cannot find symbol class BR
Error:(16, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(27, 13) error: cannot find symbol class BottomsheetAttendeeCheckInBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/events/EventsListAdapter.java
Error:(11, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(12, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(75, 23) error: cannot find symbol class EventLayoutBinding
Error:(79, 33) error: cannot find symbol class EventLayoutBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/events/viewholders/EventsHeaderViewHolder.java
Error:(5, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(9, 13) error: cannot find symbol class EventSubheaderLayoutBinding
Error:(11, 35) error: cannot find symbol class EventSubheaderLayoutBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/attendees/viewholders/AttendeeViewHolder.java
Error:(7, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(11, 19) error: cannot find symbol class AttendeeLayoutBinding
Error:(13, 31) error: cannot find symbol class AttendeeLayoutBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/data/EventRepository.java
Error:(7, 46) error: cannot find symbol class Attendee_Table
Error:(9, 46) error: cannot find symbol class Event_Table
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/checkin/AttendeeCheckInPresenter.java
Error:(8, 46) error: cannot find symbol class Attendee_Table
/home/shell/Git Projects/open-event-orga-app/app/src/main/java/org/fossasia/openevent/app/event/attendees/StickyHeaderAdapter.java
Error:(12, 46) error: package org.fossasia.openevent.app.databinding does not exist
Error:(29, 9) error: cannot find symbol class AttendeeSubheaderLayoutBinding
Error:(31, 27) error: cannot find symbol class AttendeeSubheaderLayoutBinding
/home/shell/Git Projects/open-event-orga-app/app/src/main/res/layout/attendee_layout.xml
Error:(38, 33) Could not find accessor org.fossasia.openevent.app.data.models.Attendee.firstName 
/home/shell/Git Projects/open-event-orga-app/app/src/main/res/layout/bottomsheet_attendee_check_in.xml
Error:(47, 73) Could not find accessor org.fossasia.openevent.app.data.models.Attendee.firstName 
/home/shell/Git Projects/open-event-orga-app/app/src/main/res/layout/event_layout.xml
Error:(28, 35) Could not find accessor org.fossasia.openevent.app.data.models.Event.thumbnail 
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: Found data binding errors.
Information:BUILD FAILED
Information:Total time: 14.356 secs
Information:31 errors
Information:0 warnings`

**Comment by iamareebjamal** [comment]
Did you do a clean build, should work fine IMO, if not, try opening in Android Studio and install lombok plugin

**Comment by Shailesh351** [comment]
@iamareebjamal It's strange i am still getting errors. I have cleaned the project. Installed lombok plugin.

**Comment by iamareebjamal** [comment]
@arp95 @rohanagarwal94 @shreyasnbhat Can you guys please test this too? I think this is because of dbflow but I am not facing any errors

**Comment by mejariamol** [comment]
@iamareebjamal  please have a look at this.
https://github.com/Raizlabs/DBFlow/issues/1084

It seems dbflow will never support lombok without kotlin

**Comment by iamareebjamal** [comment]
But it's working for me. Did you try it? Try opening the model classes after installing lombok plugin so that it generates the code

**Comment by iamareebjamal** [comment]
@mejariamol It's a shame if it doesn't work, we shouldn't be really maintaining the model boilerplate.

@Shailesh351 Can you please do me a favour? Can you try making model attributes package private (without modifiers) and check if it's working

**Comment by Shailesh351** [comment]
@iamareebjamal No luck. Still getting errors.

**Comment by iamareebjamal** [comment]
Hmm, well, let's scrap it then

**Comment by iamareebjamal** [comment]
@arp95 @shreyasnbhat @mejariamol Please try this once before I close

**Comment by arp95** [comment]
@iamareebjamal getting the same errors as @Shailesh351 . no luck with this.

**Comment by iamareebjamal** [comment]
Guys, last time, can you try this -> https://stackoverflow.com/a/43448940/3309666 

:smile:

**Comment by Shailesh351** [comment]
@iamareebjamal previous errors are gone. Getting other incompatible types error
```
Information:Gradle tasks [clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugUnitTestSources, :app:compileDebugAndroidTestSources]
Warning:File for type 'com.raizlabs.android.dbflow.config.OrgaDatabaseorga_database_Database' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
/home/shell/Git Projects/open-event-orga-app/app/build/generated/source/apt/debug/org/fossasia/openevent/app/databinding/BottomsheetAttendeeCheckInBinding.java
Error:(201, 117) error: incompatible types: Attendee cannot be converted to boolean
Error:(203, 115) error: incompatible types: Attendee cannot be converted to boolean
Error:(205, 117) error: incompatible types: Attendee cannot be converted to boolean
Error:(207, 123) error: incompatible types: Attendee cannot be converted to boolean
/home/shell/Git Projects/open-event-orga-app/app/build/generated/source/apt/debug/org/fossasia/openevent/app/databinding/AttendeeLayoutBinding.java
Error:(138, 109) error: incompatible types: Attendee cannot be converted to boolean
Error:(140, 108) error: incompatible types: Attendee cannot be converted to boolean
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 12.161 secs
Information:7 errors
Information:2 warnings
```

**Comment by iamareebjamal** [comment]
Can you please clean and retry, this time even travis didn't fail

**Comment by mejariamol** [comment]
@iamareebjamal 
`checkedIn()` method is making conflict with data binding checkedIn. It worked for me by replacing the method to `withCheckedIn()`.

**Comment by iamareebjamal** [comment]
Oh Yeah! Thanks a lot

**Comment by iamareebjamal** [comment]
@Shailesh351 @arp95 Please review

**Comment by iamareebjamal** [comment]
@niranjan94 Please merge

**Pull request merged**
