### PR TITLE
Feat #659: Add Config.gradle file for package version

### LINKED ISSUE #659: Add config.gradle file for maintaining package version
**Is it a ?**

- [ ] Bug Report

- [X] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

image
Currently this is the way for maintaining version of different android packages

**Expected Behaviour**

This might look a bit clumsy in the future so how about creating a new file where all the information regarding version numbers can be stored.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by S2606**
Fixes #659

### CODE REVIEW

**Comment by S2606** [comment]
@iamareebjamal Please review

**Comment by iamareebjamal** [comment]
The build is failing, please fix it first

**Comment by iamareebjamal** [comment]
@S2606 Status?

**Comment by S2606** [comment]
@iamareebjamal Fixing in a day

**Comment by S2606** [comment]
@iamareebjamal Creating a new PR due to some issue in my local repo

**Pull request closed without merging**
