### PR TITLE
fix: Fixed auto refresh for create new sponsers fragment and delete sponsers fragment

### LINKED ISSUE #1552: Sponsers list is not refreshed automatically when we delete sponsers
**Describe the bug**
Sponsers list is not refreshed automatically when we delete sponsers

**To Reproduce**

**Screenshots**

ezgif com-video-to-gif

**Smartphone Info:**

Redmi Note 4
Android Nougat

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by tavishjain**
Fixes #1552 and #1489 

Checklist:

- [X] I have checked for PMD and check-style issues 
- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream development branch.

Changes: Removed a not condition which was not allowing the list to refresh

Screenshots for the change:
ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by ShridharGoel** [comment]
@tavishjain Updates? Are you working on this?

**Comment by tavishjain** [comment]
@ShridharGoel I was having my exams, which got over today. Will continue from today

**Comment by tavishjain** [comment]
@Masquerade0097 this is what this fix does. When the forceload parameter is true, it loads the list from the network. Previously this was set to *!forceload*, and when the forceload was passed as true, it was acting as false.

**Comment by ShridharGoel** [comment]
I don't think this is the right approach. 

@iamareebjamal Your views?

**Comment by iamareebjamal** [comment]
Wrong logic.

**Comment by tavishjain** [comment]
Ok then, I'll think of another approach of solving this

**Comment by ShridharGoel** [comment]
Done in #1651 and #1652

**Comment by ShridharGoel** [comment]
Fixed. Please close this.

**Pull request closed without merging**
