### PR TITLE
feat: Show order details with other ticket details (#653)

### LINKED ISSUE #653: Show minorder and maxorder details with other ticket details
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When the ticket details are shown there is no mention of min order and max order values

**Expected Behaviour**

Minorder and Maxorder details should be there

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AkshayCHD**
Fixes #653 

Changes: Minumum and maximum order details are made visible to the user

Screenshots for the change: 
screenshot_1519521379

### CODE REVIEW

**Comment by AkshayCHD** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
Don't use text all caps and use strings.xml placeholders

**Comment by AkshayCHD** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
Add colon

**Pull request merged**
