### PR TITLE
chore: Break UtilModel into SharedPreferenceModel

### LINKED ISSUE #345: Create SharedPreferenceModel class
Sub issue of #342 

taking this up.

### PR DESCRIPTION
**Pull request by mejariamol**
To be merged after #301 
fixes #345

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please review the last commit.

**Comment by iamareebjamal** [comment]
Why was the JSONAPI commit included? This is an independent issue

**Comment by mejariamol** [comment]
Clearing conflicts would not require if any after merging JSONAPI commit. I will just rebase then.

**Comment by mejariamol** [comment]
@iamareebjamal please review.

**Pull request merged**
