### PR TITLE
Ticket form min. and max. field validation#721

### LINKED ISSUE #721: Provide form validation for Create Ticket Form
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

In the 'Minimum Order' field, if the user enters a value which is greater than the value entered in the 'Maximum Order' field, an `HTTP 422 UNPROCESSABLE ENTITY` error is encountered.

**Expected Behaviour**

In the snack bar, instead of the error, the cause of the error should be displayed in order to make the app more user-friendly.

**Steps to reproduce it**
1. Enter value `x` in 'Minimum Order' field
2. Enter value `y` in 'Maximum Order' field, such that `x>y`.
3. Click the 'tick' FAB to create the ticket.

**LogCat for the issue**
```
03-06 18:23:31.926 18089-18425/org.fossasia.eventyay I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.UM.5.3_RB1.06.00.01.211.056_msm8937_64_refs/tags/AU_LINUX_ANDROID_LA.UM.5.3_RB1.06.00.01.211.056__release_AU (I48a9d37399)
                                                                   OpenGL ES Shader Compiler Version: XE031.08.00.00
                                                                   Build Date: 10/18/16 Tue
                                                                   Local Branch: 
                                                                   Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.UM.5.3_RB1.06.00.01.211.056
                                                                   Local Patches: NONE
                                                                   Reconstruct Branch: NOTHING
03-06 18:23:31.929 18089-18425/org.fossasia.eventyay I/OpenGLRenderer: Initialized EGL, version 1.4
03-06 18:23:31.968 18089-18425/org.fossasia.eventyay E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
03-06 18:23:37.358 18089-18089/org.fossasia.eventyay I/Logger: List of items successfully loaded with count: 1
03-06 18:23:37.386 18089-18425/org.fossasia.eventyay E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
03-06 18:23:37.488 18089-18425/org.fossasia.eventyay D/OpenGLRenderer: endAllStagingAnimators on 0x5596e69b20 (RippleDrawable) with handle 0x5596ad94e0
03-06 18:23:39.736 18089-18089/org.fossasia.eventyay V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b8c8b3b
03-06 18:23:39.736 18089-18089/org.fossasia.eventyay V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@7e57258
03-06 18:23:39.816 18089-26185/org.fossasia.eventyay D/AbstractObservableBuild: Loaded class org.fossasia.openevent.app.common.data.models.Ticket From Disk on Thread RxCachedThreadScheduler-5
03-06 18:23:39.836 18089-18089/org.fossasia.eventyay I/Logger: List of items successfully loaded with count: 1
03-06 18:23:40.533 18089-18089/org.fossasia.eventyay V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@cb088c
03-06 18:23:40.533 18089-18089/org.fossasia.eventyay V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b557bd5
03-06 18:23:40.691 18089-18089/org.fossasia.eventyay I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
03-06 18:23:40.695 18089-18089/org.fossasia.eventyay I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
03-06 18:23:40.837 18089-18425/org.fossasia.eventyay E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
03-06 18:23:40.858 18089-18089/org.fossasia.eventyay V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@d67ae40
03-06 18:23:40.858 18089-18089/org.fossasia.eventyay V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1bce179
03-06 18:23:42.794 18089-18320/org.fossasia.eventyay I/art: Starting a blocking GC Explicit
03-06 18:23:42.849 18089-18320/org.fossasia.eventyay I/art: Explicit concurrent mark sweep GC freed 42654(1906KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 22MB/37MB, paused 668us total 52.384ms
03-06 18:23:43.586 18089-18089/org.fossasia.eventyay V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@616782b
03-06 18:23:52.205 18089-26186/org.fossasia.eventyay W/System.err: WARNING: could not load Java7 Path class
03-06 18:23:52.529 18089-26186/org.fossasia.eventyay D/OkHttp: --> POST https://open-event-api-dev.herokuapp.com/v1/tickets http/1.1
03-06 18:23:52.529 18089-26186/org.fossasia.eventyay D/OkHttp: Content-Type: application/vnd.api+json
03-06 18:23:52.529 18089-26186/org.fossasia.eventyay D/OkHttp: Content-Length: 276
03-06 18:23:52.530 18089-26186/org.fossasia.eventyay D/OkHttp: {"data":{"type":"ticket","attributes":{"max-order":2,"min-order":4,"name":"yu","sales-ends-at":"2018-03-16T18:23:40.741+05:30","sales-starts-at":"2018-03-06T18:23:40.741+05:30","ticket-delegate":{},"type":"free"},"relationships":{"event":{"data":{"type":"event","id":"30"}}}}}
03-06 18:23:52.530 18089-26186/org.fossasia.eventyay D/OkHttp: --> END POST (276-byte body)
03-06 18:23:54.986 18089-26186/org.fossasia.eventyay D/OkHttp: <-- 422 UNPROCESSABLE ENTITY https://open-event-api-dev.herokuapp.com/v1/tickets (2455ms)
03-06 18:23:54.986 18089-26186/org.fossasia.eventyay D/OkHttp: Connection: keep-alive
03-06 18:23:54.986 18089-26186/org.fossasia.eventyay D/OkHttp: Server: gunicorn/19.7.1
03-06 18:23:54.986 18089-26186/org.fossasia.eventyay D/OkHttp: Date: Tue, 06 Mar 2018 12:53:55 GMT
03-06 18:23:54.986 18089-26186/org.fossasia.eventyay D/OkHttp: Content-Type: application/vnd.api+json
03-06 18:23:54.986 18089-26186/org.fossasia.eventyay D/OkHttp: Content-Length: 202
03-06 18:23:54.986 18089-26186/org.fossasia.eventyay D/OkHttp: Access-Control-Allow-Origin: *
03-06 18:23:54.987 18089-26186/org.fossasia.eventyay D/OkHttp: Via: 1.1 vegur
03-06 18:23:54.987 18089-26186/org.fossasia.eventyay D/OkHttp: {"errors": [{"source": {"pointer": "/data/attributes/max-order"}, "title": "Unprocessable Entity", "detail": "max-order should be greater than min-order", "status": 422}], "jsonapi": {"version": "1.0"}}
03-06 18:23:54.987 18089-26186/org.fossasia.eventyay D/OkHttp: <-- END HTTP (202-byte body)
03-06 18:23:55.027 18089-18089/org.fossasia.eventyay E/Logger: An exception occurred : HTTP 422 UNPROCESSABLE ENTITY
                                                               retrofit2.adapter.rxjava2.HttpException: HTTP 422 UNPROCESSABLE ENTITY
                                                                   at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
                                                                   at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
                                                                   at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
                                                                   at io.reactivex.Observable.subscribe(Observable.java:11442)
                                                                   at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                   at io.reactivex.Observable.subscribe(Observable.java:11442)
                                                                   at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
                                                                   at io.reactivex.Observable.subscribe(Observable.java:11442)
                                                                   at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                   at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
                                                                   at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                   at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

**Screenshots of the issue**
http422

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mishuvs**
Fixes #721 

Changes: Checks if minimum order is less than maximum order.

Screenshots for the change: 
NA

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@mishuvs This is open for a long time. Please fix the build as this is just a trivial change

**Comment by iamareebjamal** [comment]
@mishuvs Please confirm

**Comment by mishuvs** [comment]
Yes. I'll fix this today.

**Comment by mishuvs** [comment]
@iamareebjamal Please review.

**Pull request merged**
