### PR TITLE
feat: Integrate Error Prone

### LINKED ISSUE #984: Error Prone Integration
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore

### Feature Request

**Feature Description**

This will help in catching the errors in the compile time itself.
https://github.com/tbroyer/gradle-errorprone-plugin

**Would you like to work on the issue?**

Yes! @iamareebjamal

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #984 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream development branch.

Changes: 

Integration of error prone in the project.
https://github.com/tbroyer/gradle-errorprone-plugin

### CODE REVIEW

**Comment by ShridharGoel** [comment]
@iamareebjamal Any problem with Travis? It's stuck on 'Job received'.

**Comment by ShridharGoel** [comment]
Also, closing and reopening is not restarting the CircleCI and Travis build.

**Comment by iamareebjamal** [comment]
Leave Travis. Currently, Error Prone is still not working with lombok

So we'll only be able to merge this on next release

**Comment by ShridharGoel** [comment]
Ok but build was successful locally

**Comment by iamareebjamal** [comment]
https://circleci.com/gh/fossasia/open-event-orga-app/2360?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://travis-ci.org/fossasia/open-event-orga-app/builds/511893460?utm_source=github_status&utm_medium=notification

Both failed with same error

**Comment by ShridharGoel** [comment]
@iamareebjamal It's working fine now.

**Comment by iamareebjamal** [comment]
Great

**Pull request merged**
