### PR TITLE
fix: Prevent navigation drawer content from overlapping with the status bar

### LINKED ISSUE #1464: Navigation drawer content overlaps with status bar
**Describe the bug**
Navigation drawer content overlaps with status bar.

**Screenshots**
screenshot_2019-01-25-20-54-27-389_com eventyay organizer

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

- Other: @iamareebjamal Is this intentional? Should it be rectified or not?

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1464 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 
Now, the content in navigation drawer would not overlap with the status bar.

Screenshots for the change:
screenshot_2019-01-26-02-08-08-613_com eventyay organizer

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Not correct, status bar should remain transparent

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal  How to get email verified, after server reset I am getting "only verified accounts can create events" whenever I tries creating events.

**Comment by ShridharGoel** [comment]
> Not correct, status bar should remain transparent

I'm not sure what the problem is but the status bar is not becoming transparent if fitsSystemWindows is set to false. I did changes in the theme and also tried setting the status bar colour in the onCreate() method of MainActivity but it didn't work.
@iamareebjamal Can you help?

**Comment by mariobehling** [comment]
@ShridharGoel Please ask your co-developers and others to help with that.

**Comment by Ankit0080** [comment]
has anyone found solution of this problem ? i am having same issue

**Pull request closed without merging**
