### PR TITLE
feat: Add a color picker for Tracks Fragment

### LINKED ISSUE #1061: Implementing color picker in Create Tracks Fragment
### Feature Request

**Feature Description**
While creating tracks the user needs to enter the color code. It will be better if there is color picker inplace of it.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fixes #1061 

Changes: 
- A color picker library is being used for the implementation of Color Picker

Updated Screenshots for the change:
ezgif com-resize 14

### CODE REVIEW

**Comment by iamareebjamal** [comment]
The original issue has discussion as to what behaviour should the color picker have

**Comment by srv-twry** [comment]
@sridharjajoo Check here: https://github.com/fossasia/open-event-orga-app/issues/871

**Comment by sridharjajoo** [comment]
@iamareebjamal I am trying to set the text color but it always gets set to either black or white. Even the api docs mention this point about font color. Will it be still possible to update the font color?

Parameter | Description | Type | Required
-- | -- | -- | --
name | Name of the track | string | yes
description | Description of the track | string | -
color | Color code of the track (can be in hex notation(e.g, #a04b4b) or decimal notation from 0 to 255(e.g, rgba(160, 75, 75, 0.5))) | string | yes
font-color | Font Color of the track (black/white: no user role - automatically updated) | string | -

**Comment by iamareebjamal** [comment]
Yeah sorry, font color is automatically set

**Comment by sridharjajoo** [comment]
@iamareebjamal @Masquerade0097 @mishuvs Kindly review.

**Comment by iamareebjamal** [comment]
Fix codacy issue. Also, user should see the auto generated color

**Comment by iamareebjamal** [comment]
User still cannot see the generated color until the field is clicked

**Comment by sridharjajoo** [comment]
In what form should the user see the color. Should I add a background tint to the palette image view?

**Comment by iamareebjamal** [comment]
A little square after the edittext would be fine

**Comment by sridharjajoo** [comment]
@iamareebjamal Does this look fine? I have updated the screenshot

**Pull request merged**
