### PR TITLE
chore: Simplify the app

### LINKED ISSUE #1724: Simplify the app
**Describe the chore**
Extra features need to be commented out from the app, as discussed.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1724

### CODE REVIEW

**Comment by iamareebjamal** [comment]
What was the point of implementing roles and speaker call if it was to commented out?

**Comment by iamareebjamal** [comment]
Instead of commenting it out. Make it configurable through env variables in gradle file.

**Comment by ShridharGoel** [comment]
@iamareebjamal In the meeting, @mariobehling told me to comment out these features as they are not needed in the app and can be used from the frontend when required.

**Comment by iamareebjamal** [comment]
That'll make the efforts made into the app development futile and development hours wasted. Just add the option to enable and disable features through configuration and we'll add the necessary values in the build process

Ref: https://github.com/luggit/react-native-config/blob/master/android/dotenv.gradle

**Comment by mariobehling** [comment]
@iamareebjamal We decided in the meeting to comment it out for now as we only have one developer working on this. We want to focus on the basic functionality first. We can add an "expert mode" to the app later in GSoC.

@ShridharGoel We are now approaching the second term of GSoC. You should be sticking to best practices by now. Please always add screenshots and for major changes a test apk. It should have been here. There is no description in the PR here neither. Simply saying "fixes issue" is not enough. We need a description, screenshot etc. See how other people are doing it e.g. in the frontend project. You are not following best practices.

**Pull request merged**
