### PR TITLE
chore: Update README.md

### LINKED ISSUE #587: chore: Update README.md
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [x] Chore
    

**Description**

The README currently used for the project does not have screenshots of the forgot password feature. Which involve 2 new screens - ForgotPasswordByTokenFragment and ResetPassordByTokenFragment. 

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #587

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@Masquerade0097 Please use github media content for images

**Comment by Masquerade0097** [comment]
@iamareebjamal I've made the required changes, please review.

**Comment by iamareebjamal** [comment]
I didn't mean this. I meant like this ->

ml

**Comment by Masquerade0097** [comment]
@iamareebjamal Ok, I've made the changes accordingly, have a look.

**Comment by iamareebjamal** [comment]
`This branch is out-of-date with the base branch` Can you please rebase the branch?

**Comment by Masquerade0097** [comment]
I'm sending another PR for this issue, this branch has gotten messy on git.

**Pull request closed without merging**
