### PR TITLE
upgrade to Ionic version 3.0

### LINKED ISSUE #80: Upgrade to Ionic 3.0
Ionic Version 3 has been released based on Angular 4.0.
Project should be upgraded to include new features in platform like Lazy Loading which is now supported.

I am working on this.

### PR DESCRIPTION
**Pull request by betterclever**
fixes #80

### CODE REVIEW

**Comment by betterclever** [comment]
Yeah Sure. Working on it.

**Comment by betterclever** [comment]
@niranjan94 The build is failing at lint part. I mentioned that before too that changes being done at the time of summit were not following proper lint. I am adding a commit to refactor code to maintain standards according to TSLint .

**Comment by betterclever** [comment]
@niranjan94  apk link: https://transfer.sh/tl1VY/orga-app.apk

**Comment by betterclever** [comment]
@niranjan94 I am a little confused, TSlint suggests using const in for loop for iteration variable
Line 1234 in build: ERROR: 7:14   prefer-const  Identifier 'key' is never reassigned; use 'const' instead of 'let'.

SMH it sounds unreasonable to me.

**Comment by niranjan94** [comment]
@betterclever the change tslint config so that `prefer-const` rule is not an error but only a warning

**Comment by betterclever** [comment]
@niranjan94 Build is fixed. Please have a look. Should I squash commits?

**Pull request merged**
