### PR TITLE
fix: Invalidate invalid field message on text changes

### LINKED ISSUE #1391: Invalid field message while signing up doesn't go away even on increasing the number of characters in password
**Describe the bug**

"Invalid field. The minimum number of characters is 6" message while signing up doesn't go away even on increasing the number of characters in password. It only goes away after clicking the sign up button.

**To Reproduce**
1. Go to the sign up page.
2. Type a password which is less than 6 characters.
3. Click on some other field.
4. "Invalid field. The minimum number of characters is 6" error will be displayed.
5. Now, increase the number of characters and click on some other field.
6. The error will still be shown.

**Expected behavior**

The error should have disappeared on increasing the number of characters.

**Screenshots**

After entering a password which is less than 6 characters:
img_20181108_121730

Then, even after changing it to a proper password:
screenshot_2018-11-08-12-17-06-403_com eventyay organizer

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1391 

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 

Now the invalid field message will disappear when the user corrects the length of the password and then clicks on some other field.

Screenshots:

ezgif com-video-to-gif 1

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Better question is why the textwatxher is not getting fired? We should fix that instead of adding more listeners

**Comment by ShridharGoel** [comment]
@Masquerade0097 Done.

**Comment by ShridharGoel** [comment]
@iamareebjamal Is this better?

**Comment by iamareebjamal** [comment]
Fix indentation

**Pull request merged**
