### PR TITLE
fix: Update .travis.yml to fix apk build

### LINKED ISSUE #88: Fix travis build and apk upload
travis build and apk upload need to be fixed for the new native android app

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #88

- Fixes dependency versions
- Fixes install orderings
- Fixes lint issues
- Logs the output of tests and lint on travis console

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Now failing due to entire play services bundle included in the app. Fixing...

**Comment by iamareebjamal** [comment]
Issue in lint now. Fixing...

**Comment by iamareebjamal** [comment]
Fixed but after disabling checks. Looking like travis has a bug.

Have found the issue. Let's see :crossed_fingers:

**Comment by iamareebjamal** [comment]
Done @niranjan94. :+1:

**Comment by iamareebjamal** [comment]
Let me just test one more thing please

If it works without disabling check for NewApi, it'll be awesome

**Comment by iamareebjamal** [comment]
Working correctly.

You may merge now

**Comment by iamareebjamal** [comment]
Should I squash or let it be?

**Comment by iamareebjamal** [comment]
Done @niranjan94

**Comment by niranjan94** [comment]
@iamareebjamal looks good. Feel free to merge once the travis build passes. 

And also, never make branches on the main repo. Please fork this into your account and make a branch there in future.

**Comment by iamareebjamal** [comment]
Also, we should consider circle ci as it is faster and supports uploading artifacts which can be easily viewed. 

Like release apk, debug apk, and full hosted html of test, lint warning and errors

Travis needs an S3 account for doing so

**Comment by iamareebjamal** [comment]
Yeah, sorry for that. I clicked on edit on my repo, still it created a branch here. Won't happen again

**Comment by niranjan94** [comment]
@iamareebjamal what we follow here at fossasia is, we push built apk's onto an `apk` branch on the repo. We would like to do the same here. For now, we will be staying on Travis CI for uniformity.

**Comment by iamareebjamal** [comment]
@niranjan94 True about the apk build, but it is easier to see the lint and test results as html. Susi Android uses circle ci. I wasn't suggesting moving from Travis, rather having circle ci has well

**Comment by iamareebjamal** [comment]
@niranjan94 I don't have write access to the repo. Please merge :)

**Comment by niranjan94** [comment]
@iamareebjamal you do have write access to the repo. (That's why github created a branch for you here when you pressed edit.)

**Comment by iamareebjamal** [comment]
I thought so, but it was showing that I wasn't authorized to make merge on master branch as it was protected

**Comment by niranjan94** [comment]
@iamareebjamal lemme check that

**Pull request merged**
