### PR TITLE
Retains fragment instances for same event

### LINKED ISSUE #191: Event containing fragments are not retained
fragment instances are not retained while switching for same event.

Expected: fragments must be retained for same event

### PR DESCRIPTION
**Pull request by mejariamol**
fixes #191

### CODE REVIEW

**Comment by mejariamol** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
@mejariamol Please test now and see if the log messages for loading attendees display on changing of tabs. I'm currently AFK

**Comment by mejariamol** [comment]
@iamareebjamal yes. I debugged. Now fragment instances are retained. But the attendees will be loaded everytime (from network initially and from disk thereafter) since presenter's `start()` call is called in `onActivityCreated` which is no issue.

**Comment by iamareebjamal** [comment]
But they shouldn't load on tab switches.

Well, I'll think about it later and fix it

**Comment by mejariamol** [comment]
For that to happen presenter's data loading calls should be separated from view's interactions, And these shall be called in fragment's `onCreate`.

**Pull request merged**
