### PR TITLE
Remove unnecessary dependencies

### LINKED ISSUE #22: Don't download obsolete packages
Some of the Android SDK downloaded are obsolete and not needed.
The [travis log](https://travis-ci.org/fossasia/open-event-orga-app/builds/155379322#L2041) itself mentions this, so removing these will speed up the build process.
```
Installing Archives:
  Preparing to install archives
  Downloading Android Support Library, revision 23.2.1 (Obsolete)
  Installing Android Support Library, revision 23.2.1 (Obsolete)
    Installed Android Support Library, revision 23.2.1 (Obsolete)
  Done. 1 package installed.
```

### PR DESCRIPTION
**Pull request by the-dagger**
Fixes #22 @niranjan94 Please review and merge

### CODE REVIEW

**Comment by the-dagger** [comment]
@niranjan94 Why do we need both android-23 and 24 sdk package?

**Comment by niranjan94** [comment]
@the-dagger right now ionic builds with 23. I'll remove 23 once I change it.

**Comment by niranjan94** [comment]
@the-dagger right now ionic builds with 23 ... I'll remove it once I fix that.

**Comment by the-dagger** [comment]
@niranjan94 Ok cool.

**Pull request merged**
